### ISSUE TITLE
Change the base package from wagner to something generic

### ISSUE THREAD

**Issue by 19WAS85** [19WAS85/coollection#9]
This lib have been used more than I expected, due to lack of Java 8 in many environments. Let's change this base package to be generic, I'm sure your boss don't want to see my name in the classes 🙃

This is the package you need to import today:

```
import static com.wagnerandade.coollection.Coollection.*;
```

What should be a good generic path?

**Comment by alansferreira** [comment]
Hi man, well, i'm rename in my fork to org.simple.coollection.*, but you can choose something more generic... kkkk

**Comment by 19WAS85** [comment]
It's ok to me. Can you generate a PR? I'm with no Java env here.

**Comment by viniciusrdacosta** [comment]
> It's ok to me. Can you generate a PR? I'm with no Java env here.

I made my first contribution in PR #10

**Comment by 19WAS85** [comment]
Holly fuck... you did it... Thanks bro!

**Comment by alansferreira** [comment]
Thank dudes ... I have more contributions on my fork
like `in`,` sum` and improvements in [Phanton](https://github.com/alansferreira/coollection/blob/master/coollection/src/main/java/org/simple/coollection/reflection/Phanton.java) to use getters, setters and property path, but I'm running with other things ...
In a few days, I'll merge my code.

For now i still working to my dinner kkk, and another personal projects like [cds-parsers](https://github.com/alansferreira/cds-parsers) and [db_designer](https://github.com/alansferreira/db_designer), if you guys can help me or share, I would appreciate it kkkkk
